---
title: "R Notebook"
output: html_notebook
---



```{r}
library(shiny)
library("dplyr")
library("tidyr")
library("ggplot2")
library("ggridges")
 library(lubridate)
 library(plotly)
library(tidyverse)
data = read_csv("./data/479_tidy_data.csv")
data
```

```{r}
t = c()
d = str_split(data$email, "@")
for(i in 1:length(data$email)){
  t = c(t,d[[i]][2] )
}
data['college'] = data$institution
```

```{r}
data$college
```
s

```{r}
library("tidygraph")
library("gridExtra")
library("networkD3")
library("tidygraph")
tempata <- filter(data,college=='mit.edu') 
E <- data.frame(
  source = tempata$college,
  target =  tempata$name,
  value = tempata$num_commit
)

G <- as_tbl_graph(E, directed = FALSE) %>% activate(edges) %>%
  mutate(value = factor(value) )%>%  activate(nodes)%>%
  mutate(type = name %in% tempata$college)
G
```
```{r, fig.width=10,fig.height=10}
library("ggraph")
ggraph(G, layout = 'kk') + 
  geom_edge_link(colour = "#d3d3d3", width = 0.5, alpha = 0.55) +
  geom_node_label(aes(label = name, col = type, size = type)) +
  scale_color_manual(values = c("#BF4545", "#225C73")) +
  scale_size_discrete(range = c(2.5, 5)) +
  scale_fill_brewer(palette = "Set2") +
 coord_fixed() +
  theme_void()
```


```{r}
library(shiny)
library("dplyr")
library("tidyr")
library("ggplot2")
library("ggridges")
 library(lubridate)
 library(plotly)
library(tidyverse)

colleges <- pull(data, college) %>%
   unique() %>%
   na.omit()

 ### functions used in app
networkDiagram <- function(tempata) {
  E <- data.frame(
    source = tempata$college,
    target =  tempata$name,
    value = tempata$num_commit
  )
  
  G <- as_tbl_graph(E, directed = FALSE) %>% activate(edges) %>%
    mutate(value = factor(value) )%>%  activate(nodes)%>%
    mutate(type = name %in% tempata$college)

  ggraph(G, layout = 'kk') + 
  geom_edge_link(colour = "#d3d3d3", width = 0.5, alpha = 0.55) +
  geom_node_label(aes(label = name, col = type, size = type)) +
  scale_color_manual(values = c("#BF4545", "#225C73")) +
  scale_size_discrete(range = c(2.5, 5)) +
  scale_fill_brewer(palette = "Set2") +
 coord_fixed() +
  theme_void()
 }

 ### definition of app
ui <- fluidPage(
   titlePanel("Github University Analysis"),
   selectInput("colleges", "College", colleges),
   plotOutput("network")
 )

 server <- function(input, output) {
   
    college_subset <- reactive({
     filter(data,college==input$colleges) 
   })

   output$network <- renderPlot({
     networkDiagram(college_subset())
   })
   
 }

app <- shinyApp(ui, server)
app
```

